baseURL = "http://shawn111.eco-city.tw/"
languageCode = "en-us"
title = "My New Hugo Site"
description = "A Hugo Theme built with Bootstrap"
sidebarDescription = "A Hugo Theme built with Bootstrap"
sidebarFreeText = "A optional paragraph of free text. Set to blank in config.toml to clear..."
theme = "strange-case"
publishDir = "docs"
