baseURL = "http://shawn111.eco-city.tw/"
languageCode = "en-us"
title = "鄰長阿伯"
description = "王榮祥 鄰長阿伯 翠屏45"
theme = "strange-case"
publishDir = "docs"


[params]
        colorScheme = "scheme-darkbrown"
        dateformat = "Jan 2, 2006"
        description = "翠屏45 王榮祥"
        sidebarDescription = "王榮祥 鄰長阿伯 翠屏45"
        sidebarFreeText = ""
        piwikSiteID = ""
        piwikURL = ""

[[menu.main]]
        name = "Hugo"
        post = "<span class='glyphicon glyphicon-fire'></span>"
        url = "http://gohugo.io"

[[menu.main]]
        name = "Bootstrap"
        post = "<span class='glyphicon glyphicon-ok'></span>"
        url = "http://getbootstrap.com"
